med1=int(input('Digite a média do primeiro bimestre:'))
med2=int(input('Digite a média do segundo bimestre:'))
med3=int(input('Digite a média do terceiro bimestre:'))
med4=int(input('Digite a média do quarto bimestre:'))
media=round((med1+med2+med3+med4)/4,2)
print('sua média é',media)